### DISCUSSION TITLE
Setup for dummies !!!

### DISCUSSION THREAD

**Discussion by Quattrohead** [tfyoung/esphome-junctek_kgf#7] [General]
Hello,
I am no programmer at all but a good electro-mechanical engineer.
As such, I am slowly working out how to use HA with my home and would like to add this module to it.
I have the Junctek and RS485 to UART and USB converters and the HA computer is near enough to connect directly via USB.
Can you give me some idea of how to set this up in HA.
Thanks, Kevin.

**Comment by tfyoung** [comment]
Hi Kevin,

Sorry for the delayed reply. Things have been busy lately. I'm not sure whether to hope this reply is useful, or that you've manged to solve your problem already.

The way this works is via esphome, so you'll also need an esp chip wired to an RS485 UART. Either esp8266 or esp32. That esp chip would then use WIFI to connect to HA. There are lots of tutorials on esphome with the esp chips.

It would also be possible to have it work directly plugged into HA via the USB, but you'd need to essentially rewrite this module from scratch in python to work directly with HA, not esphome.

**Reply by Quattrohead** [reply]
I have found esphome to be very difficult to get my head around, I can initially configure an esp8266 but then it disappears from HA but is still on my network.
I will try again.
How do I use "ESPHOME Config" file, do I need to install the .py/.cpp/.h/.py files ? Sorry I know nothing about YAML files but I do have Studio Code Server installed.
The TX/RX pin numbers I am fine with and I am sure I can figure out which "sensors" I want to add.
Cheers.

**Reply by tfyoung** [reply]
There is no need to copy any files with esphome.
You should simply be able to copy the yaml example In the README (copied below) and paste it in the esphome setup below the default config that sets up the wifi etc.

The external_components section tells it to pull down this module that parses the serial output and assigns it the various sensors. The uart tells the esp how to communicate with the uart you've connected and the final config tells it which sensor values you want to show up and various config options (address and invert_config).

```
external_components:
  - source: github://tfyoung/esphome-junctek_kgf

uart:
  tx_pin: 26
  rx_pin: 27
  baud_rate: 115200

sensor:
  - platform: junctek_kgf
    address: 1
    invert_current: true
    voltage:
      name: "Battery Voltage"
    current:
      name: "Battery Current"
    battery_level:
      name: "Battery Level"
    temperature:
      name: "Battery Temperature"
```

You can try checking the logs inside esphome to see if there are any errors or issues you're hitting
